[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"  
buildContext = "backend"       # ‚Üê Le dice a Railway que entre a backend

[deploy]
startCommand = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"